services:
  yaml-form-generator:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8502:8501"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8502/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s